export type SiteContent = {
  headerBrand: string;
  portfolioProjectsLabel: string; portfolioCertificationsLabel: string; portfolioTechStackLabel: string;
  contactFormTitle: string; contactNameLabel: string; contactEmailLabel: string; contactMessageLabel: string; contactMessagePlaceholder: string; contactSubmitLabel: string;
  homeProjectsLabel: string; homeTechnologiesLabel: string; homeCuriosityLabel: string; homeProjectsCta: string; homeAboutCtaLabel: string;
  homeAvailability: string; homeTitleLine1: string; homeTitleLine2: string; homeAboutTitle: string; homeAboutAccent: string; homeAboutCta: string; homeFeaturedTitle: string; homeFeaturedAccent: string; homeContactTitle: string; homeContactAccent: string; aboutTitleLine1: string; aboutTitleLine2: string; aboutAvailability: string; aboutLocation: string; aboutQuote: string; aboutSkillsNote: string; aboutEducationNote: string; portfolioTitleLine1: string; portfolioTitleLine2: string; portfolioDescription: string; contactTitleLine1: string; contactTitleLine2: string; contactIntro: string; footerBrand: string; footerCopy: string; navHomeLabel: string; navAboutLabel: string; navPortfolioLabel: string; navContactLabel: string;
};

export const defaultSiteContent: SiteContent = {
  headerBrand: "LOKO-DADE.", portfolioProjectsLabel: "Projets", portfolioCertificationsLabel: "Certifications", portfolioTechStackLabel: "Tech Stack", contactFormTitle: "Envoyer un message", contactNameLabel: "Votre nom", contactEmailLabel: "Votre adresse e-mail", contactMessageLabel: "Votre message", contactMessagePlaceholder: "Parlez-moi de votre projet...", contactSubmitLabel: "Envoyer le message", homeProjectsLabel: "Projets réalisés", homeTechnologiesLabel: "Technologies", homeCuriosityLabel: "Curiosité", homeProjectsCta: "Voir mes projets", homeAboutCtaLabel: "À propos de moi", homeAvailability: "Disponible pour de nouveaux projets", homeTitleLine1: "Full-Stack", homeTitleLine2: "Developer.", homeAboutTitle: "Des idées utiles.", homeAboutAccent: "Du code qui compte.", homeAboutCta: "Découvrir mon parcours", homeFeaturedTitle: "Ce que je construis", homeFeaturedAccent: "en ce moment.", homeContactTitle: "Un projet en tête ?", homeContactAccent: "Parlons-en.", aboutTitleLine1: "Une développeuse", aboutTitleLine2: "orientée impact.", aboutAvailability: "Disponible pour de nouveaux projets", aboutLocation: "Basée au Bénin · Travail à distance", aboutQuote: "La technologie a le plus de valeur quand elle répond à un besoin réel.", aboutSkillsNote: "Les outils que j’utilise pour passer de l’idée à une solution fiable.", aboutEducationNote: "Des bases pluridisciplinaires pour comprendre les enjeux au-delà du code.", portfolioTitleLine1: "Portfolio", portfolioTitleLine2: "Showcase", portfolioDescription: "Découvrez mes projets, mes formations et les technologies que j’utilise pour construire des solutions numériques.", contactTitleLine1: "Construisons", contactTitleLine2: "quelque chose.", contactIntro: "Une idée, un besoin ou simplement envie d’échanger ? Écrivez-moi, je vous répondrai avec plaisir.", footerBrand: "MERVYLKD.", footerCopy: "Conçu & développé avec soin · 2024", navHomeLabel: "Accueil", navAboutLabel: "À propos", navPortfolioLabel: "Portfolio", navContactLabel: "Contact",
};
