/* Charte aqua/noir : formulaire fonctionnel relié à la procédure tRPC publique contact.send. */
import React, { FormEvent, useState } from "react";
import { ArrowUpRight, Github, Linkedin, Mail, MapPin, Send } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { getAnalyticsSessionId } from "@/lib/analytics";
import { defaultSiteContent } from "@/lib/site-content";

export default function Contact() {
  const [sent, setSent] = useState(false);
  const profileQuery = trpc.portfolio.profile.get.useQuery();
  const contentQuery = trpc.portfolio.content.get.useQuery();
  const profile = profileQuery.data;
  const content = contentQuery.data ?? defaultSiteContent;
  const mutation = trpc.contact.send.useMutation({ onSuccess: () => setSent(true) });
  const socialClickTracker = trpc.portfolio.analytics.trackSocialClick.useMutation();
  const trackSocialClick = (platform: "github" | "linkedin") => socialClickTracker.mutate({ sessionId: getAnalyticsSessionId(), path: "/contact", platform });
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(false); const form = new FormData(event.currentTarget); try { await mutation.mutateAsync({ name: String(form.get("name") || ""), email: String(form.get("email") || ""), message: String(form.get("message") || "") }); event.currentTarget.reset(); } catch { /* L’état d’erreur est présenté dans le formulaire. */ } };
  return <main className="inner-page contact-page"><div className="page-intro"><div><p className="kicker">04 / Contact</p><h1>{content.contactTitleLine1}<br /><span>{content.contactTitleLine2}</span></h1></div><p className="intro-paragraph">{content.contactIntro}</p></div><div className="contact-layout"><form className="contact-form" onSubmit={submit} noValidate><div className="form-heading"><span>01</span><h2>{content.contactFormTitle}</h2></div><label>{content.contactNameLabel}<input required minLength={2} name="name" placeholder={content.contactNameLabel} /></label><label>{content.contactEmailLabel}<input required type="email" name="email" placeholder={content.contactEmailLabel} /></label><label>{content.contactMessageLabel}<textarea required minLength={10} name="message" rows={5} placeholder={content.contactMessagePlaceholder} /></label><button className="aqua-button" type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Envoi en cours..." : sent ? "Message envoyé" : content.contactSubmitLabel} <Send size={16} /></button>{sent && <p className="form-success">Votre message a bien été enregistré. Merci pour votre prise de contact.</p>}{mutation.isError && <p className="form-error">Le message n’a pas pu être envoyé. Vérifiez les champs puis réessayez.</p>}</form><aside className="contact-info">{profileQuery.isLoading ? <p className="data-state" role="status">Chargement des coordonnées…</p> : !profile ? <p className="data-state" role="status">Les coordonnées seront bientôt publiées.</p> : <><div className="info-block"><span className="info-icon"><Mail size={17} /></span><div><small>E-mail</small><a href={`mailto:${profile.email}`}>{profile.email}</a></div></div><div className="info-block"><span className="info-icon"><MapPin size={17} /></span><div><small>Localisation</small><p>{content.aboutLocation}</p></div></div><div className="info-block"><span className="info-icon"><Github size={17} /></span><div><small>GitHub</small><a href={profile.github} target="_blank" rel="noreferrer" onClick={() => trackSocialClick("github")}>GitHub <ArrowUpRight size={13} /></a></div></div><div className="info-block"><span className="info-icon"><Linkedin size={17} /></span><div><small>LinkedIn</small><a href={profile.linkedin} target="_blank" rel="noreferrer" onClick={() => trackSocialClick("linkedin")}>Voir mon profil <ArrowUpRight size={13} /></a></div></div></>}</aside></div></main>;
}
