import { FormEvent, useEffect, useState } from "react";
import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { defaultSiteContent, SiteContent } from "@/lib/site-content";
import { trpc } from "@/lib/trpc";

type EducationForm = { title: string; place: string; year: string; displayOrder: number };
const emptyEducation: EducationForm = { title: "", place: "", year: "", displayOrder: 0 };

const contentGroups: Array<{ title: string; fields: Array<{ key: keyof SiteContent; label: string; multiline?: boolean }> }> = [
  { title: "En-tête & navigation", fields: [{ key: "headerBrand", label: "Marque de l’en-tête" }, { key: "navHomeLabel", label: "Navigation accueil" }, { key: "navAboutLabel", label: "Navigation à propos" }, { key: "navPortfolioLabel", label: "Navigation portfolio" }, { key: "navContactLabel", label: "Navigation contact" }] },
  { title: "Accueil", fields: [{ key: "homeAvailability", label: "Disponibilité" }, { key: "homeTitleLine1", label: "Titre principal ligne 1" }, { key: "homeTitleLine2", label: "Titre principal ligne 2" }, { key: "homeAboutTitle", label: "Titre section à propos" }, { key: "homeAboutAccent", label: "Accent section à propos" }, { key: "homeAboutCta", label: "CTA à propos" }, { key: "homeFeaturedTitle", label: "Titre projets récents" }, { key: "homeFeaturedAccent", label: "Accent projets récents" }, { key: "homeContactTitle", label: "Titre contact" }, { key: "homeContactAccent", label: "Accent contact" }] },
  { title: "À propos", fields: [{ key: "aboutTitleLine1", label: "Titre ligne 1" }, { key: "aboutTitleLine2", label: "Titre ligne 2" }, { key: "aboutAvailability", label: "Disponibilité" }, { key: "aboutLocation", label: "Localisation" }, { key: "aboutQuote", label: "Citation", multiline: true }, { key: "aboutSkillsNote", label: "Note compétences", multiline: true }, { key: "aboutEducationNote", label: "Note formations", multiline: true }] },
  { title: "Portfolio & contact", fields: [{ key: "portfolioTitleLine1", label: "Portfolio ligne 1" }, { key: "portfolioTitleLine2", label: "Portfolio ligne 2" }, { key: "portfolioDescription", label: "Description portfolio", multiline: true }, { key: "contactTitleLine1", label: "Contact ligne 1" }, { key: "contactTitleLine2", label: "Contact ligne 2" }, { key: "contactIntro", label: "Introduction contact", multiline: true }, { key: "footerBrand", label: "Marque du pied de page" }, { key: "footerCopy", label: "Texte du pied de page" }] },
];

export function AdminSiteContent() {
  const query = trpc.portfolio.content.get.useQuery();
  const utils = trpc.useUtils();
  const [form, setForm] = useState<SiteContent>(defaultSiteContent);
  const [feedback, setFeedback] = useState("");
  useEffect(() => { if (query.data) setForm(query.data); }, [query.data]);
  const mutation = trpc.portfolio.content.update.useMutation({ onSuccess: () => { setFeedback("Contenus du site enregistrés."); utils.portfolio.content.get.invalidate(); }, onError: error => setFeedback(`Erreur : ${error.message}`) });
  const submit = (event: FormEvent) => { event.preventDefault(); setFeedback(""); mutation.mutate(form); };
  return <section className="admin-single editorial-content-section"><form className="admin-form" onSubmit={submit}><div className="admin-form-heading"><div><p className="kicker">Édition globale</p><h2>Contenu du site</h2></div><Save size={19} className="aqua-text" /></div><p className="admin-help">Modifiez les textes visibles dans l’en-tête, l’accueil, À propos, le portfolio, Contact et le pied de page.</p>{contentGroups.map(group => <fieldset className="editorial-fieldset" key={group.title}><legend>{group.title}</legend><div className="admin-fields">{group.fields.map(field => <label className={field.multiline ? "field-wide" : ""} key={field.key}>{field.label}{field.multiline ? <textarea rows={3} value={form[field.key]} onChange={event => setForm({ ...form, [field.key]: event.target.value })} /> : <input required value={form[field.key]} onChange={event => setForm({ ...form, [field.key]: event.target.value })} />}</label>)}</div></fieldset>)}<button className="aqua-button" disabled={mutation.isPending}><Save size={15} /> {mutation.isPending ? "Enregistrement…" : "Enregistrer les contenus"}</button>{feedback && <p className="admin-feedback" role="status">{feedback}</p>}</form></section>;
}

export function AdminEducation() {
  const query = trpc.portfolio.education.list.useQuery();
  const utils = trpc.useUtils();
  const [form, setForm] = useState<EducationForm>(emptyEducation);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [feedback, setFeedback] = useState("");
  const create = trpc.portfolio.education.create.useMutation({ onSuccess: () => { setFeedback("Formation créée."); setForm(emptyEducation); utils.portfolio.education.list.invalidate(); }, onError: error => setFeedback(`Erreur : ${error.message}`) });
  const update = trpc.portfolio.education.update.useMutation({ onSuccess: () => { setFeedback("Formation modifiée."); setEditingId(null); setForm(emptyEducation); utils.portfolio.education.list.invalidate(); }, onError: error => setFeedback(`Erreur : ${error.message}`) });
  const remove = trpc.portfolio.education.delete.useMutation({ onSuccess: () => { setFeedback("Formation supprimée."); utils.portfolio.education.list.invalidate(); }, onError: error => setFeedback(`Erreur : ${error.message}`) });
  const submit = (event: FormEvent) => { event.preventDefault(); setFeedback(""); if (editingId) update.mutate({ id: editingId, data: form }); else create.mutate(form); };
  const busy = create.isPending || update.isPending || remove.isPending;
  return <section className="admin-section"><form className="admin-form" onSubmit={submit}><div className="admin-form-heading"><div><p className="kicker">Formation & certification</p><h2>{editingId ? "Modifier une formation" : "Ajouter une formation"}</h2></div>{editingId ? <button type="button" className="icon-button" onClick={() => { setEditingId(null); setForm(emptyEducation); }} aria-label="Annuler"><X size={16} /></button> : <Plus size={19} className="aqua-text" />}</div><div className="admin-fields"><label className="field-wide">Intitulé<input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Licence en..." /></label><label>Organisme<input required value={form.place} onChange={event => setForm({ ...form, place: event.target.value })} placeholder="Université ou organisme" /></label><label>Année<input pattern="\\d{4}" value={form.year} onChange={event => setForm({ ...form, year: event.target.value })} placeholder="2026" /></label><label>Ordre<input type="number" min="0" value={form.displayOrder} onChange={event => setForm({ ...form, displayOrder: Number(event.target.value) })} /></label></div><button className="aqua-button" disabled={busy}><Save size={15} /> {busy ? "Enregistrement…" : editingId ? "Enregistrer" : "Créer la formation"}</button>{feedback && <p className="admin-feedback" role="status">{feedback}</p>}</form><div className="admin-list"><div className="admin-list-heading"><div><p className="kicker">Formations publiées</p><span>{query.isLoading ? "Chargement…" : `${query.data?.length ?? 0} formation(s)`}</span></div></div>{query.data?.length ? query.data.map(item => <article className="admin-item" key={item.id}><div><strong>{item.title}</strong><span>{item.place} · {item.year || "—"}</span><small>Ordre {item.displayOrder}</small></div><div className="admin-item-actions"><button className="icon-button" onClick={() => { setEditingId(item.id); setForm({ title: item.title, place: item.place, year: item.year || "", displayOrder: item.displayOrder }); }} aria-label={`Modifier ${item.title}`}><Pencil size={15} /></button><button className="icon-button danger" onClick={() => window.confirm(`Supprimer ${item.title} ?`) && remove.mutate({ id: item.id })} aria-label={`Supprimer ${item.title}`}><Trash2 size={15} /></button></div></article>) : <p className="admin-empty">Aucune formation publiée.</p>}</div></section>;
}
